# kube-prometheus-stack values
prometheus:
  prometheusSpec:
    retention: 7d  # Set retention period to 7 days (cost savings)
    # Comment out storage to use memory storage (no persistent cost)
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: gp2
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 10Gi  # Set to 10GB considering free tier

grafana:
  adminPassword: "admin123"  # In production, manage with secrets
  # Comment out persistence to use memory storage (no persistent cost)
  # persistence:
  #   enabled: true
  #   storageClassName: gp2
  #   size: 5Gi
  service:
    type: LoadBalancer  # Use LoadBalancer for external access
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

alertmanager:
  alertmanagerSpec:
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

# Resource limits configuration (considering free tier)
kube-state-metrics:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

node-exporter:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Enable default dashboards
defaultDashboardsEnabled: true
