apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels: { app: test-app }
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30080
  selector: { app: test-app }
